### ISSUE TITLE
Use a smaller Runtime image

### ISSUE THREAD

**Issue by ibotty** [openshift-s2i/s2i-go#12]
See https://github.com/openshift/source-to-image/blob/master/docs/runtime_image.md.

**Comment by jasonmccallister** [comment]
Docker released (still on edge) multi-stage builds in CE 17.05. Is this something that can be updated on the docs included in the Openshift build process?

See this blog post for some additional context: https://medium.com/travis-on-docker/multi-stage-docker-builds-for-creating-tiny-go-images-e0e1867efe5a

**Comment by 0xmichalis** [comment]
Closing in favor of https://github.com/sclorg/golang-container
