### ISSUE TITLE
Make s2i-go buildable on OpenShift

### ISSUE THREAD

**Issue by dlbewley** [openshift-s2i/s2i-go#18]
Lack of `s2i/bin` dir in each version context dir makes builds in openshift difficult. PR coming

**Comment by jawnsy** [comment]
Thanks Dale!

I wanted to keep all the scripts together to reduce maintenance burden (the thinking being that multiple copies means having to update multiple scripts every time a change is made). How are you building them, using the Docker build strategy on OpenShift? Would it help if these were published to DockerHub?

**Comment by dlbewley** [comment]
In production I generally prefer to build the images myself rather than pull from Dockerhub. In the case of `s2i-python` I need to make local changes during the build.

**eg**

```bash
oc new-project dlbewley
oc create -f https://raw.githubusercontent.com/dlbewley/s2i-go/contextdir-s2i/imagestream.yaml
oc create -f https://raw.githubusercontent.com/dlbewley/s2i-go/contextdir-s2i/buildconfig.yaml
oc start-build go-17-centos7 --follow
```

In my case I use a project to which all developers are granted image pull access. Now users can

```bash
oc new-app dlbewley/go-17-centos7~https://gitlab/my-go.git
```

**Comment by jawnsy** [comment]
I've repurposed this issue to track the requirement to make this easily buildable on OpenShift, as I think that's a great idea. A PR would be most welcome!

**Comment by 0xmichalis** [comment]
Closing in favor of https://github.com/sclorg/golang-container
