### ISSUE TITLE
maintainer needed?

### ISSUE THREAD

**Issue by goern** [openshift-s2i/s2i-go#22]
hey all, I see that some ppl use/need s2i-go, but the repo is kind of frozen. Do we have an active maintainer? Do we need on?

cc: @bparees @danmcp

**Comment by bparees** [comment]
we should probably see if the SCL team that maintains most of the other language images at this point would be interested in creating an official version of this and maintaining it.  @hhorak wdyt?

**Comment by hhorak** [comment]
There are plans to have golang s2i image (just one version) quite soon, but just as tech-preview. Would that be enough for your needs? @goern

**Comment by goern** [comment]
@hhorak sure I think there is lots of good work happening in this repo's fork network, we should somehow try to get it back in sync with this repo...

**Comment by jtescher** [comment]
Any updates on this? Would be happy to help out if work is happening on it

**Comment by hhorak** [comment]
Hey, actually we have a different repo that should be maintained better -- https://github.com/sclorg/golang-container and an s2i image is now available as https://hub.docker.com/r/centos/go-toolset-7-centos7/
