### ISSUE TITLE
Assemble script should use idiomatic Go project structure (GOPATH/src/github.com/...)

### ISSUE THREAD

**Issue by jawnsy** [openshift-s2i/s2i-go#6]
Special thanks to **Alexander Sokolovsky** for reporting this via email. These are Alexander's notes, with formatting cleaned up slightly for GitHub.

Considerations (needs discussion):
- We should accept the "project path" as an environment variable to the build
- If the environment variable is not defined, we should fall back to the current behaviour

> “assemble” script copies source code to $HOME/go/src/main.
> It’s different from git sub-path of source code.
> It’s not problem for simple go app but usually go app includes sub-folder packages.
> 
> Lets imagine test-app has sub-folder “pkg” with "pkg.go” code file.
> 
> So project structure is:
> $HOME/go/src/main/main.go
> $HOME/go/src/main/pkg/pkg.go
> 
> “main.go” imports “pkg”:
> import "github.com/openshift-s2i/s2i-go/1.6/test/test-app/pkg"
> 
> (it’s usual approach of go developers to use github path to import packages inside application.
> 
> For example:
> 
> https://github.com/openshift/origin/blob/master/pkg/gitserver/gitserver.go
> 
> it includes client packages using git path:
> 
> ```
>     "github.com/openshift/origin/pkg/client"
>     "github.com/openshift/origin/pkg/generate/git"
> ```
> 
> So “go get -v ./...” searches “pkg” here:
> 
> ./vendor/ github.com/openshift-s2i/s2i-go/1.6/test/test-app/pkg
> $HOME/go/src/github.com/openshift-s2i/s2i-go/1.6/test/test-app/pkg
> 
> and doesn’t find!
> 
> “got get” ignores “$HOME/go/src/main/pkg" path!
> 
> As result “go get” imports “pkg” to the folder: $HOME/go/src/github.com/openshift-s2i/s2i-go/1.6/test/test-app/pkg
> 
> It means “go build” ignores $HOME/go/src/main/pkg/pkg.go file and uses $HOME/go/src/github.com/openshift-s2i/s2i-go/1.6/test/test-app/pkg/pkg.go instead to build.
> 
> There few problems for production here:
> 1. double source code downloading
> 2. you will get error if you try to build code from non-public repo – “go get” doesn’t know repo’s credentials
> 3. if you try to build “branch/tag” sources using s2i “ref” command you get the conflict:
> 
> “$HOME/go/src/main/main.go” from “branch/tag”
> “$HOME/go/src/github.com/openshift-s2i/s2i-go/1.6/test/test-app/pkg/pkg.go” from MASTER (“go get” downloads from MASTER only)
> 
> This is problem – project files from different branch/tag.
> 
> Resolution:
> 
> You need to copy source code into git-like folder before build. Project structure should be:
> 
> $HOME/go/src/github.com/openshift-s2i/s2i-go/1.6/test/test-app/main.go
> $HOME/go/src/github.com/openshift-s2i/s2i-go/1.6/test/test-app/pkg/pkg.go
> 
> I’m not sure that my solution is the best but I hope it helps.
> 
> I provide git URL as environment variable to “assemble” file and parse path to create source code correct path:
> 
> ```
> echo "---> Clarify the root package for go application"
> 
> ROOT_PACKAGE=$(echo "$SOURCE_REPOSITORY_URL" | sed -re "s/(https:\/\/|git@)([^?]+)\.git/\2/g" | sed -re "s/:/\//g")
> 
> if [[ -n "${CONTEXT_DIR/[ ]*\n/}" ]]
> then
>     ROOT_PACKAGE="$ROOT_PACKAGE/$CONTEXT_DIR"
>     echo "CONTEXT_DIR is \"$CONTEXT_DIR\", so root package is \"$ROOT_PACKAGE\""
> else
>     echo "CONTEXT_DIR is empty, so root package is \"$ROOT_PACKAGE\""
> fi
> 
> SOURCE_CODE="$GOPATH/src/$ROOT_PACKAGE"
> 
> echo "---> Installing application source in folder \"$SOURCE_CODE\""
> 
> mkdir -p $SOURCE_CODE
> cd $SOURCE_CODE
> cp -Rf /tmp/src/. ./
> ```

**Comment by amsokol** [comment]
Dear Jonathan,

When I create OpenShift app based on my OpenShift template I provide git url and context dir via ENV variables to “assemble” script implicitly for user.
But it doesn’t work for “s2i build”.
Yes, I know I can manually provide git url and context dir via “--env” but it's workaround.
Could you please ask guys from s2i team is it possible to get git url and context dir inside “assemble” script?
There is no any documentation how to get “s2i build” options inside “assemble” script.

**Comment by jawnsy** [comment]
Hey Alexander @amsokol, I've forwarded your question and tried to provide some context here: https://github.com/openshift/source-to-image/issues/527 - since your comment is not specific to `s2i-go`

**Comment by jawnsy** [comment]
I just came across this: https://golang.org/doc/go1.4#canonicalimports

> Go 1.4 introduces an annotation for package clauses in Go source that identify a canonical import path for the package. If an import is attempted using a path that is not canonical, the go command will refuse to compile the importing package.
>
> The syntax is simple: put an identifying comment on the package line. For our example, the package clause would read:
>
> `package pdf // import "rsc.io/pdf"`

This means that we can detect the appropriate path to use by parsing the canonical import path, which is another way to get the information we need.  It also occurs to me that there may be multiple main binaries (e.g. a Go project with `cmd/foo/foo.go` and `cmd/bar/bar.go` resulting in both `foo` and `bar` binaries, so manually specifying an environment variable might be the optimal way to go.)

**Comment by 0xmichalis** [comment]
Closing in favor of https://github.com/sclorg/golang-container
