### ISSUE TITLE
Create OpenShift template

### ISSUE THREAD

**Issue by jawnsy** [openshift-s2i/s2i-go#7]
We need a template for OpenShift, to make it easier to build Go applications from source.

**Comment by amsokol** [comment]
Hi, if my code is ok please push updated images openshift/go-14-centos7, openshift/go-15-centos7, openshift/go-16-centos7 to Docker Hub. OpenShift templates require the following images:
docker.io/openshift/go-14-centos7
docker.io/openshift/go-15-centos7
docker.io/openshift/go-16-centos7

**Comment by jasonmccallister** [comment]
@amsokol can you also update this to include Go 1.8?

**Comment by amsokol** [comment]
Dear @themccallister , @ssendev ,

I'm not contributing `openshift-s2i/s2i-go` any more.
You can ask @jawnsy .

But I have and support my own implementation of golang template: [amsokol/openshift-golang-template](https://github.com/amsokol/openshift-golang-template) that you can easy use.
It has some features that `openshift-s2i/s2i-go` has not:
- golang 1.8
- based on ImageStream
- flexible golang project structure (you can see [here](https://github.com/amsokol/openshift-golang-template/tree/master/example) example with `best practice` golang project structure)
- heath checks
- [golang official](https://github.com/golang/dep) (prototype) dependency manager and I can easy add others dep managers
- tested on latest version on OpenShift

Thanks,
Aleksandr

**Comment by 0xmichalis** [comment]
Closing in favor of https://github.com/sclorg/golang-container
