### ISSUE TITLE
Error when "make build VERSION=1.6"

### ISSUE THREAD

**Issue by amsokol** [openshift-s2i/s2i-go#8]
when I try to build your 1.6 image I got the following error:

make build VERSION=1.6
hack/build.sh: line 63: easy_install: command not found
make: **\* [build] Error 127

**Comment by jawnsy** [comment]
Hey Alexander, thanks for the report! Oops, it seems our instructions need to be updated. Please install Python 2 (use the `python2-setuptools` package on Fedora) as the `easy_install` tool is used to get `docker-squash` (used for pruning unused layers from built images).

You could also try running with `SKIP_SQUASH=1` to avoid running docker-squash (just means you'll have unnecessary layers and a slightly larger resulting image), though I haven't tried that myself.

**Comment by amsokol** [comment]
Dear Jonathan,

Thank you for reply.

If I add SKIP_SQUASH=1 to make - everything is OK.

Thanks!
